### ISSUE TITLE
Explore QLTYSH coverage reporter

### ISSUE THREAD

**Issue by reactive-firewall** [reactive-firewall/python-repo#85]
explore new code coverage reporter tool:

```yaml
- uses: qltysh/qlty-action/coverage@v1
  with:
    token: {{secrets.QLTY_COVERAGE_TOKEN}}
    files: reports/lcov.info
```
